baseURL: https://szk302.dev/
title: Szk302 開発ブログ
paginate: 20
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-212898668-1

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Szk302 開発ブログ"
    description: "日々の開発で得られた知見を書き出します"
    keywords: [開発, Dev, Blog, PaperMod]
    author: Szk302
    # author: ["Me", "You"] # multiple authors
    images: ["https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42"]
    # DateFormat: "January 2, 2006"
    DateFormat: "2006-01-02T15:04:05Z07:00"
    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: true
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42"
        favicon16x16: "https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42?p=16"
        favicon32x32: "https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42?p=32"
        apple_touch_icon: "https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42"
        safari_pinned_tab: "https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42"

    label:
        text: "Szk302 開発ブログ"
        # icon: /apple-touch-icon.png
        icon: https://www.gravatar.com/avatar/d9669165d1baf624cedab4afc3dfcc42
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "開発の日々..."
        # Content: Welcome to my blog

    socialIcons:
        - name: twitter
          url: "https://twitter.com/Sszk302"
        # - name: stackoverflow
        #   url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/szk302/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        # hidden: true # hide everywhere but not in structured data
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        # hiddenInList: true # hide on list pages and home
        # hiddenInSingle: true # hide on single page
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/szk302/dev-blog-content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        # - identifier: posts
        #   name: posts
        #   url: posts
        #   weight: 5
        - identifier: categories
          name: カテゴリ
          url: /categories/
          weight: 10
        - identifier: tags
          name: タグ
          url: /tags/
          weight: 20
        - name: 検索
          url: search/
          weight: 30
        - identifier: profile
          name: プロフィール
          url: fixed/profile
          weight: 40
        - identifier: blog
          name: このブログについて
          url: fixed/blog
          weight: 50
        # - identifier: example
        #   name: example.org
        #   url: https://example.org
        #   weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

markup:
  asciidocext:
    extensions:
      - asciidoctor-html5s
      - asciidoctor-diagram
    workingFolderCurrent: true
    trace: true
    attributes:
      my-base-url: 'https://localhost/'
      my-attribute-name: my value
