name: Build blog builder image

on:
  workflow_dispatch: 
    inputs:
      hugo_version:
        description: 'Hugo version'
        required: false
        default: '0.80.0'
      asciidoctor_version:
        description: 'Asciidoctor version'
        required: false
        default: '1.14.0'
  push:
    branches: [ main ]
    paths:
      - 'docker-images/hugo/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker-images/hugo/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      # -
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.CR_PAT }}
      # -
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: docker-images/hugo
      #     push: true
      #     tags: "ghcr.io/szk302/dev-blog-builder:hugo-${{ github.event.inputs.hugo_version }}_asciidoctor-${{ github.event.inputs.asciidoctor_version }}"
      #     build-args: |
      #       HUGO_VERSION=${{ github.event.inputs.hugo_version }}
      #       ASCIIDOCTOR_VERSION=${{ github.event.inputs.asciidoctor_version }}
      #     secrets: |
      #       GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-images/hugo/Dockerfile
          push: true
          tags: "ghcr.io/szk302/dev-blog-builder:hugo-${{ github.event.inputs.hugo_version }}_asciidoctor-${{ github.event.inputs.asciidoctor_version }}"
          build-args: |
            HUGO_VERSION=${{ github.event.inputs.hugo_version }}
            ASCIIDOCTOR_VERSION=${{ github.event.inputs.asciidoctor_version }}
      - 
        name: Write tool version
        run: |
            echo HUGO_VERSION=${{ github.event.inputs.hugo_version }} > tool_version.env
            echo ASCIIDOCTOR_VERSION=${{ github.event.inputs.asciidoctor_version }} >> tool_version.env
      - 
        name: Commit files
        run: |
            git config --local user.email "69619077+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add tool_version.env
            git commit -m "Add changes" -a
      - 
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      # - 
      #   name: Build the Docker image
      #   run: docker build . --file ./docker-images/hugo/Dockerfile --tag ghcr.io/szk302/dev-blog-builder:hugo_asciidoctor --build-arg HUGO_VERSION="${{ github.event.inputs.hugo_version }}" --build-arg ASCIIDOCTOR_VERSION="${{ github.event.inputs.asciidoctor_version }}" \
      # - 
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: user/app:latest
