name: Build Szk302 dev blog
on:
  workflow_dispatch: 
    inputs:
      build_image_name:
        description: 'Image name'
        default: ''
        required: true
  workflow_call:
    inputs:
      build_image_name:
        description: 'Image name'
        default: ''
        required: true
        type: string
    # secrets:
    #   token:
    #     required: false
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.build_image_name }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Fetch content
        run: git submodule update --init --recursive
      - 
        name: Build dev blog
        run: hugo --destination public
      - 
        name: Archive generated html
        uses: actions/upload-artifact@v2
        with:
          name: blog-dev-html
          path: public

